### ISSUE TITLE
Image resizer doesn't work on attached image.

### ISSUE THREAD

**Issue by nesterenes** [FBerthelot/angular-images-resizer#12]
Please download the attached. This image will not process and crashes the browser. All other jpg, jpeg, png file types work. It seems specific to all images downloaded from Google Image Backup.

Thank you!

![pb252545](https://cloud.githubusercontent.com/assets/1128121/11607694/0a590b22-9b1f-11e5-94bb-0c6e89fa5941.JPG)

**Comment by nesterenes** [comment]
PS. Excellent too. Much appreciated!

**Comment by FBerthelot** [comment]
Hello @nesterenes ,

Sorry for the time i've took to answer you. I've been busy as i never been busy in my life....

I've tried your picture, and it worked well. What is the code are you using ? You can try your image by at this website: http://fberthelot.github.io/angular-images-resizer/#/

Merry Christmas ! :santa:

**Comment by nesterenes** [comment]
Hey @FBerthelot ,

Thanks so much for looking at this. I've spent a bit more time debugging,
and found that the code is stuck in an infinite loop... with the image
actually increasing in size instead of decreasing in size.

I narrowed it down to the divideStrategy variable within the service, and
was able to successfully execute with the following modification:

// ORIGINAL CODE
var divideStrategy =  sizeOfTheImage / (size * 2) <= 1 ? *0.9* :
 sizeOfTheImage / (size * 2.3);

// REVISED CODE
var divideStrategy =  sizeOfTheImage / (size * 2) <= 1 ? *1.1* :
 sizeOfTheImage / (size * 2.3);


It confuses me that this image resize works your site but not mine. I
attached a sample controller with the image hard-coded, and the breaking
issue. However at this point my issue is resolved.

Please let me know if you think I should submit a pull request. I would be
happy to do so (however as it is not broken on your site with the same
image... I'm not sure if it's necessary).

Thank you again!
@nesterenes

**Comment by FBerthelot** [comment]
Thank you so much for this detailed issue.

I've decided to change the way i work on this project. And I've detected some bugs on the service with a new version of the demonstration site.
So I've decided to release a new version soon(I hope before 4th of January).

See you soon and have a good year's end celebration :tada:

**Comment by FBerthelot** [comment]
Hello @nesterenes,

I've finally found the time to released a new version of the angular-images-resizer (2.0.1). :fireworks: 
Be careful, there is a breaking change in the new version.

I hope everything is working now :smile:.
Re-open this issue, if the bug still there.

Thank you.

**Comment by nesterenes** [comment]
Thank you! I've got some backlog tasks for image upload. I'll keep you
posted.
N
