### ISSUE TITLE
Issue with Resizing in 2.0 Release - Octet Resize

### ISSUE THREAD

**Issue by nesterenes** [FBerthelot/angular-images-resizer#19]
1) Navigate to:
   http://fberthelot.github.io/angular-images-resizer/#/
2) Upload attached image.
![apr08-02-1280](https://cloud.githubusercontent.com/assets/1128121/15133674/f780c32a-1632-11e6-996d-5cb5323be6ee.jpg)

3) choose Octet resize.
4) App freezes. Contact me if it doesn't freeze. I can email you the original.

**Comment by FBerthelot** [comment]
Hey,
Ok, I investigate it. 

Do you have any error from the console, or it seam to freeze the browser ?

**Comment by FBerthelot** [comment]
I've rewritten the function to resize with a size in octet.

It should work now with the version 2.0.2!
Tell me if it doesn't.

Have a nice day.

**Comment by nesterenes** [comment]
Awesome! I was just reviewing the diffs. I'll re-test today. Thanks again!

On Tue, May 10, 2016 at 8:01 AM, Florent Berthelot <notifications@github.com
