### ISSUE TITLE
Resizing transparent png image turns black

### ISSUE THREAD

**Issue by prumps** [FBerthelot/angular-images-resizer#20]
When I resize a png image that has transparency, the image turns black.  I've attached an example that I tried in my own code and on your demo page.  
![test](https://cloud.githubusercontent.com/assets/5313398/15408662/2b6ac664-1dc6-11e6-87f6-e99c140984b5.png)

**Comment by FBerthelot** [comment]
Hello @prumps ,

It's not a bug, it's normal because the demo page export images in jpeg. And jpeg images don't support transparency.

It's possible to specify the output format in the service ;)

Thanks for your feedback, I will change the demo page behavior.
