### ISSUE TITLE
Service Method resizeImageBySize always returns the original image.

### ISSUE THREAD

**Issue by nesterenes** [FBerthelot/angular-images-resizer#21]
File resize-service.js line 242 else block is never triggered. It needs to be moved outside of the while block. Thanks -

**Comment by FBerthelot** [comment]
Sorry, I tottaly missed your issue :cry: 

I'm not agree, the else is called, however the demo website didn't work.

Hope it work for you, I let you answer if it's not the case.

Happy new year.
