### ISSUE TITLE
Failed to execute toDataURL

### ISSUE THREAD

**Issue by seanmavley** [FBerthelot/angular-images-resizer#22]
When I do this
```
                resizeService
                  .resizeImage($scope.formData.thumbnail, {
                    size:306,
                    sizeScale: 'ko'
                  })
                  .then(function(image) {
                    console.log(image);
                  })
                  .catch(function(error) {
                    con
```

I get this error: 
`DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at Object.resizeImageBySize (http://localhost:3000/vendor/angular-images-resizer/angular-images-resizer.js:1:2327)`

The `$scope.formData.thumbnail` is something like this: http://i.imgur.com/Nozq7GV.png

I have enabled `crossOrigin = "Anonymous"` attribute on the image element

Any workaround?

**Comment by FBerthelot** [comment]
Hello,

Did you tried to use the resize service like that: 
```javascript
resizeService
                  .resizeImage($scope.formData.thumbnail, {
                    size:306,
                    sizeScale: 'ko',
                    crossOrigin: 'Anonymous'
                  })
```

It should work :)

**Comment by seanmavley** [comment]
You're right. I was adding the crossOrigin attribute to the element in the html. Didn't notice a crossOrigin option for `resizeImage()` Thank you.
