### ISSUE TITLE
cropping?

### ISSUE THREAD

**Issue by Kateriine** [FBerthelot/angular-images-resizer#23]
Hello, I'm testing your component, which seems perfect for what I need; resizing seems to work perfectly, but cropping doesn't

**Comment by FBerthelot** [comment]
Hello,

I'm glad my service match your first needs. 😄 

Unfortunately, the service doesn't crop images it's only resize.

I'm certain you will find a service which crop images.

Good luck.

**Comment by Kateriine** [comment]
Well it’s been 2 days I’m looking for a solution, yours is the best at this time ^^
BTW, would I dare to ask you how you proceed when you need images to be cropped (to fit in a square, for example)? (if you find annoying to answer my question, simply don’t answer me, I’d understand you have much better to do) :)

I’m currently testing Angular in frontend decoupled with Wordpress CMS in backend, where I can « pregenerate » all images sizes, but I don’t like that system since it can use a lot of space if you have plenty of pictures and plenty of images sizes to generate :)

BTW2, serais-tu francophone?

**Comment by FBerthelot** [comment]
This angular service use canvas to resize images. you can look the [code resize image function](https://github.com/FBerthelot/angular-images-resizer/blob/master/src/resize-service.js#L153) in this file part of the "magic" is there.

My angular service is inspired by [this tutorial](https://blog.liip.ch/archive/2013/05/28/resizing-images-with-javascript.html) but it's only for resize. You can simply achieve a cropping with canvas like that with this tutorial : http://www.html5canvastutorials.com/tutorials/html5-canvas-image-crop/

Oui, je suis français :)

**Comment by Kateriine** [comment]
Yay, gonna check that, thank you/merci beaucoup!
