### ISSUE TITLE
npm install failed 

### ISSUE THREAD

**Issue by orrozenblat** [FBerthelot/angular-images-resizer#24]
hey , 
i get errors when i try to install the package using npm : 

npm ERR! tar.unpack untar error C:\Users\orr\AppData\Roaming\npm-cac
mages-resizer\2.0.2\package.tgz
npm WARN NGP@1.2.0 No repository field.
npm WARN NGP@1.2.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Fil
node_modules\\npm\\bin\\npm-cli.js" "install" "angular-images-resize
"--no-optional"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path C:\GIT\ng-admin\admin-shared-client\grunt\node_modules
gular-images-resizer-f60e78b8\docs\partials\api\images-resizer.servi
PicService@readFileInput
npm ERR! path Read file input and convert it into base64 file.html
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\GIT\ng-a
hared-client\grunt\node_modules\.staging\angular-images-resizer-f60e
rtials\api\images-resizer.service.readLocalPicService@readFileInput
npm ERR! enoent Read file input and convert it into base64 file.html
npm ERR! enoent ENOENT: no such file or directory, open 'C:\GIT\ng-a
hared-client\grunt\node_modules\.staging\angular-images-resizer-f60e
rtials\api\images-resizer.service.readLocalPicService@readFileInput
npm ERR! enoent Read file input and convert it into base64 file.html
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GIT\ng-admin\admin-shared-client\grunt\npm-debug.log

**Comment by FBerthelot** [comment]
Hello,

Very strange, it's work well for me.
The more strange thing in your issue is the reference to Grunt.

Maybe you should consider to clean your npm cache, clean your ./node_module directory, make sure you have fully access to your current directory and then try to reinstall `angular-image-resizer`.

If you still have the error, send the full errors (some char is missing).

Good luck :)

**Comment by orrozenblat** [comment]
hey .
i install other package just in the same way ,
the error is : 

npm ERR! tar.unpack untar error C:\Users\orr\AppData\Roaming\npm-cache\angular-i
mages-resizer\2.0.2\package.tgz
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN NGP@1.2.0 No repository field.
npm WARN NGP@1.2.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "angular-images-resizer" "--save"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! path C:\GIT\ng-admin\admin-shared-client\grunt\node_modules\.staging\an
gular-images-resizer-f60e78b8\docs\partials\api\images-resizer.service.readLocal
PicService@readFileInput
npm ERR! path Read file input and convert it into base64 file.html
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'C:\GIT\ng-admin\admin-s
hared-client\grunt\node_modules\.staging\angular-images-resizer-f60e78b8\docs\pa
rtials\api\images-resizer.service.readLocalPicService@readFileInput
npm ERR! enoent Read file input and convert it into base64 file.html'
npm ERR! enoent ENOENT: no such file or directory, open 'C:\GIT\ng-admin\admin-s
hared-client\grunt\node_modules\.staging\angular-images-resizer-f60e78b8\docs\pa
rtials\api\images-resizer.service.readLocalPicService@readFileInput
npm ERR! enoent Read file input and convert it into base64 file.html'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GIT\ng-admin\admin-shared-client\grunt\npm-debug.log

**Comment by FBerthelot** [comment]
Do you use any tool or you use directly npm ?

**Comment by orrozenblat** [comment]
directly , and im using cmd.

On Wed, Mar 29, 2017 at 5:18 PM, Florent Berthelot <notifications@github.com

**Comment by Okazari** [comment]
Could your provide the content of `C:\GIT\ng-admin\admin-shared-client\grunt\npm-debug.log` ?
