### ISSUE TITLE
Repository unavailable on Windows

### ISSUE THREAD

**Issue by JamesCullum** [FBerthelot/angular-images-resizer#26]
The folder docs/partials/api contains files, whose filenames prevents Windows from checking out the repository. This prevents developers on Windows working not only with this repository, but also all tools which have this one as a dependancy.

Renaming the files should be sufficient for a fix.
I would do it myself, but as mentioned - I can't.

**Comment by FBerthelot** [comment]
Hello,

It should be good now :)

**Comment by JamesCullum** [comment]
Thank you very much! 👍

**Comment by JamesCullum** [comment]
Sorry to bother again - can you pack the changes and tag it again?
Bower retrieves the current version 2.0.2 and downloads it, and it still contains these files.

**Comment by FBerthelot** [comment]
It's done.

Sorry, I haven't seen the github notification...
