### ISSUE TITLE
Image format issue

### ISSUE THREAD

**Issue by daupawar** [FBerthelot/angular-images-resizer#6]
When i choose .png image lib converts it to .jpg. how do i resize image with same format 
eg:- png(200x2000) to png(50x50)

**Comment by FBerthelot** [comment]
Oops sorry i didn't seen your issue before, I’ve had a wrong github notification settings...
I always convert image to jpg !
I will release a new version soon to solve your issue ;)

**Comment by daupawar** [comment]
thanks FBerthelot

**Comment by FBerthelot** [comment]
Hey i don't know if you noticed but i've created few days ago a branch with the possibility to export in the image format you want. 
Unfortunatly my test don't pass anymore so i don't merge the branch :'(
I've tested the export in png with this branch and it's work so you can use the "format-choosing" version in your bower component.
You can now set the "outputFormat" option to "image/png"  in the resizeImage function.

I just need more time to rewrite my tests...

**Comment by FBerthelot** [comment]
After a long period of inactivity, I’ve finally merged the branch ;)

**Comment by daupawar** [comment]
Hey thanks Florent, you have wrote great lib
