### ISSUE TITLE
Add angular as bower dependency

### ISSUE THREAD

**Issue by vysakhvk** [FBerthelot/angular-images-resizer#8]
When I am injecting angular-images-resizer using wiredep, the js file is loading before angular.js. I found this issue occurs because angular is not specified as a dependecy in bower.

**Comment by FBerthelot** [comment]
Hello,
That's really pertinent !
I've make the modification in PR #9. 
Thank you.

**Comment by FBerthelot** [comment]
Version 0.9.2 is released. Hope it will work for you ;)

**Comment by vysakhvk** [comment]
Thanks
